# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'es.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Lista_de_peliculas = QtWidgets.QListWidget(self.centralwidget)
        self.Lista_de_peliculas.setGeometry(QtCore.QRect(420, 20, 331, 311))
        self.Lista_de_peliculas.setObjectName("Lista_de_peliculas")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 30, 95, 135))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.anhadir_pelicula = QtWidgets.QPushButton(self.widget)
        self.anhadir_pelicula.setObjectName("anhadir_pelicula")
        self.verticalLayout.addWidget(self.anhadir_pelicula)
        self.editar_nombre_pelicula = QtWidgets.QPushButton(self.widget)
        self.editar_nombre_pelicula.setObjectName("editar_nombre_pelicula")
        self.verticalLayout.addWidget(self.editar_nombre_pelicula)
        self.quitar_pelicula = QtWidgets.QPushButton(self.widget)
        self.quitar_pelicula.setObjectName("quitar_pelicula")
        self.verticalLayout.addWidget(self.quitar_pelicula)
        self.salir = QtWidgets.QPushButton(self.widget)
        self.salir.setObjectName("salir")
        self.verticalLayout.addWidget(self.salir)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.anhadir_pelicula.setText(_translate("MainWindow", "Añadir pelicula"))
        self.editar_nombre_pelicula.setText(_translate("MainWindow", "Editar Nombre"))
        self.quitar_pelicula.setText(_translate("MainWindow", "Quitar Pelicula"))
        self.salir.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
